name: geolocation_example
description: Geolocation example
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

dev_dependencies:
  geolocation:
    path: ../

flutter:
  uses-material-design: true
